# Generated by Django 3.2.5 on 2021-07-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
